name: Alpine Test CI

on:
  push:
    branches:
    - "tmp-host-riscv64-dev"

jobs:
  build:  
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: alpine.sh {0}
    steps:
      - name: Update & Upgrade
        run: sudo apt update && sudo apt upgrade --yes
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Alpine Linux v3.20 for riscv64
        uses: jirutka/setup-alpine@v1
        with: 
          arch: riscv64
          branch: v3.20

      - name: Run script inside Alpine chroot with riscv64 emulation
        run: uname -m
        shell: alpine.sh {0}
      - name: Install dependencies
        run: apk add gcc g++ meson llvm18-dev pkgconf libressl-dev
        shell: alpine.sh --root {0}
      - name: Build
        run: | 
          meson setup build/ -Dbuildtype=release
          ninja -C build
          ninja -C build test
        shell: alpine.sh {0}


